language: sh


sudo: false


install:
  - curl -Lso shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.4/shellcheck
  - chmod +x shellcheck


script:
  - shellcheck *.sh
  - shellcheck *.bash
