language: sh


sudo: false


install:
  - curl -Lso shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.4/shellcheck
  - chmod +x shellcheck


script:
  - ./shellcheck apple-mail-rm-cache.bash
  - ./shellcheck boot2docker-binfmt-armhf.sh
  - ./shellcheck bower_cache.sh
  - ./shellcheck change-terminal-color.sh
  - ./shellcheck clean.sh
  - ./shellcheck color.sh
  - ./shellcheck curl-header.bash
  - ./shellcheck docker-cleanup
  - ./shellcheck docker-search-repos
  - ./shellcheck find_dead_symlinks.sh
  - ./shellcheck flushdns.sh
  - ./shellcheck get-arcep-freemobile-prefixes.sh
  - ./shellcheck git-log-compact.sh
  - ./shellcheck git-log-graph.sh
  - ./shellcheck git-stats.sh
  - ./shellcheck grep-no-svn.sh
  - ./shellcheck grep-v-comment.sh
  - ./shellcheck ip.sh
  - ./shellcheck itunes-match-update.bash
  - ./shellcheck list-hosts-ips.sh
  - ./shellcheck lsof-top-hosts.bash
  - ./shellcheck lsof-top-pid.bash
  - ./shellcheck makeapp.sh
  - ./shellcheck mosh-manfred.sh
  - ./shellcheck my_ip.sh
  - ./shellcheck ocs_create_rescue_server.sh
  - ./shellcheck osx-download-history.sh
  - ./shellcheck randomize_lines
  - ./shellcheck remove_pdf_password.sh
  - ./shellcheck reset_rabbitmq.sh
  - ./shellcheck restart-virtualbox.bash
  - ./shellcheck restart_vbox.sh
  - ./shellcheck socat-proxy-GETPOST-nocache
  - ./shellcheck speedup-terminal.sh
  - ./shellcheck sqli_get_num_args.sh
  - ./shellcheck -e SC2001 stallone.sh
  - ./shellcheck statsd-client
  - ./shellcheck svn-to-git.sh
  - ./shellcheck sync_gits.sh
  - ./shellcheck twitter_john.sh
  - ./shellcheck twitter_words.sh
  - ./shellcheck update_brew_list.sh
  - ./shellcheck updatedb.sh
  - ./shellcheck vagrant-ssh-manfred.sh
  - ./shellcheck wget.sh
  - ./shellcheck yossh-manfred.sh
